plugins:

    cloudify_plugin_existing_server:
        derived_from: cloudify.plugins.manager_plugin
        properties:
            url: https://github.com/ilyash/cloudify-plugin-existing-server/archive/master.zip

    cloudify_plugin_chef:
        derived_from: cloudify.plugins.agent_plugin
        properties:
            url: https://github.com/Fewbytes/cloudify-plugin-chef/archive/master.zip

imports:
    - cloudify.openstack
    - existing-server-type.yaml
    - chef-type.yaml

blueprint:
    name: existing-server-test
    nodes:
        -
            name: existing_server
            type: existing_server
            properties:
                ip: 1.2.3.4
                install_agent: true
                worker_config:
                    port: 22
                    user: ubuntu
                    key: ~/.ssh/cloudify-agents-kp-ilya.pem
        # -
        #     name: server
        #     type: cloudify.openstack.server
        #     properties:
        #         install_agent: true
        #         worker_config:
        #             port: 22
        #             user: ubuntu
        #             key: ~/.ssh/cloudify-agents-kp-ilya.pem
        #         management_network_name: cloudify-admin-network
        #         server:
        #             name: ilya-chef
        #             image_name: Ubuntu Precise 12.04 LTS Server 64-bit 20121026 (b)
        #             flavor_name: standard.small  # 2G RAM, 2 CPUs
        #             key_name: cloudify-agents-kp-ilya
        #             security_groups: [cloudify-sg-agents]
        #             userdata: |
        #                 #!/bin/bash -ex
        #                 grep -q novalocal /etc/hosts || echo "10.20.30.40 chef.novalocal" >> /etc/hosts
        -
            name: chef_node
            type: middleware_server_chef
            properties:
                chef_config:
                    chef_version: "11.10.4-1"

                    # ALT 1: server
                    # chef_server_url: "https://10.20.30.40:443"
                    # chef_validator_name: "chef-validator"
                    # chef_validation: "-----BEGIN RSA PRIVATE KEY-----\nSECRET\nLINES\n-----END RSA PRIVATE KEY-----\n"

                    # ALT 2: solo
                    chef_cookbooks: http://1.2.3.4:50000/cookbooks.tar.gz

                    chef_environment: "_default"
                    chef_attributes:
                        test_attr_1: test_val_1
                        create_file:
                            file_name: /tmp/blueprint.txt
                            file_contents: Great success!
                    runlists:
                        create:    recipe[create-file]
                        configure: null
            relationships:
                -
                    type: cloudify.relationships.contained_in
                    target: existing_server
                    # target: server
        # Just to show attributes passing chef_node -> chef_node2
        -
            name: chef_node2
            type: middleware_server_chef
            properties:
                chef_config:
                    chef_version: "11.10.4-1"

                    # ALT 2: solo
                    chef_cookbooks: http://1.2.3.4:50000/cookbooks.tar.gz

                    chef_environment: "_default"
                    chef_attributes:
                        other_file_name: {related_chef_attribute: create_file.file_name}
                        test_attr_2: test_val_2
                        create_file:
                            file_name: /tmp/blueprint2.txt
                            file_contents: {related_chef_attribute: create_file.file_name}
                    runlists:
                        establish: recipe[create-file]
            relationships:
                -
                    type: cloudify.chef.depends_on
                    target: chef_node
                -
                    type: cloudify.relationships.contained_in
                    target: existing_server
